### ISSUE TITLE
mp4 support

### ISSUE THREAD

**Issue by toshi0383** [rahulsom/lgtmin#13]
What do you think of supporting mp4 URL ?
MP4 file is much smaller than animated gif.
I implemented in my Mac client app just for fun. https://github.com/toshi0383/LGTM/pull/70

The problem is that GitHub is currently not supporting video tags at all.
But I believe they will soon or later.

**Comment by rahulsom** [comment]
@toshi0383 Thank you for the issue. I will add mp4 to the list of valid formats once github does so.
