### ISSUE TITLE
Please, consider having images served with SSL

### ISSUE THREAD

**Issue by irae** [rahulsom/lgtmin#16]
There are some free SSL entities out there. https://letsencrypt.org is one of them.

LGTM.in is not working on enterprise/hosted versions of GitHub right now because it is HTTP only.

**Comment by rahulsom** [comment]
This is currently running on Google App Engine. I'm not sure how that can be achieved. One option would be to use the appspot urls.

**Comment by irae** [comment]
I never used App-Engine (I did try betas in the past, but well, I assume 8 years is enough to pretend I don't know anything). Looks like it is pretty simple to do it once, but then you need to update every 90 days. [Here is one of such guides](http://blog.seafuj.com/lets-encrypt-on-google-app-engine).

There is also an [issue filed for Google to support the automated process](https://code.google.com/p/googleappengine/issues/detail?id=12535), you can take a look there too.

It is your choice if you want to do it every often and have HTTPS or wait for the automated process that might not ever come. Regular payed SSL certificates lasts one year only anyway, so it is not such an alien idea to do it periodically.

**Comment by rahulsom** [comment]
Thanks! I've got that working. I'll figure out how to renew it in 3 months.

**Comment by irae** [comment]
OMG! thank you very much!

[![LGTM](https://lgtm.in/p/kKqBd7q0q)](https://lgtm.in/i/kKqBd7q0q)

[:+1:](https://lgtm.in/u/kKqBd7q0q)

**Comment by irae** [comment]
Looks like HTTPS needs extra handling. I am ok with the current implementation and very grateful for your quick response. Here is something I noticed. There is two scenarios:

1. An HTTPS image that your redirect was HTTP and was breaking HTTPS only sites. You fixed that 100%.
2. An HTTP image that you before had HTTP redirect and now HTTPS redirect is still broken. Most of the hosts (tumblr and imgurl) actually have HTTPS versions of those, but we still get redirected to the HTTP version and the image is broken.

So, I guess there is more stuff you could do. Here is an example that breaks right now and could be working https://lgtm.in/i/cug77bikq -- this image could be 100% HTTPS if when you saved to the database, the person submitted HTTPS instead and all would be good. Or you can check if HTTPS is available and go with that.

I am not reopening the issue, as you actually fix what I asked for, but I though you might like to know of the edge case.

**Comment by hinaloe** [comment]
The certificate looks not correctly.

Sometimes, it return certification error because intermediate certificate is not correct configured.

ex, I access https://lgtm.in from Android, it show error screen. and `curl` too.

If you use certbot, fullchain.pem is good to use.

**Comment by rahulsom** [comment]
@hinaloe I've got an Android 7.x device, and the LetsEncrypt cert is trusted. I'm guessing you're using an older Android device.
Also Google AppEngine does not allow uploading `fullchain.pem`. I'm guessing Google has it's list of trusted roots and only certs that are issued by these roots are allowed.

**Comment by hinaloe** [comment]
I'm using Android 6.0 device, and it not trusted.
![screenshot_20170304-000255](https://cloud.githubusercontent.com/assets/5253290/23555952/1dcf3a18-006e-11e7-9bc9-48abe37cbb66.png)

GAE may allow fullchain cert.
