### ISSUE TITLE
markdown code not working on github.com

### ISSUE THREAD

**Issue by MaerF0x0** [rahulsom/lgtmin#17]
for example 

[![LGTM](https://lgtm.in/p/0KN4MtJRp)](https://lgtm.in/i/0KN4MtJRp)

**Comment by MaerF0x0** [comment]
trying +1 style [:+1:](https://lgtm.in/u/0KN4MtJRp) [:-1:](https://lgtm.in/r/0KN4MtJRp)

**Comment by MaerF0x0** [comment]
dataurl https://lgtm.in/i/0KN4MtJRp

**Comment by rahulsom** [comment]
This is what Github does.
```
<img 
   src="https://camo.githubusercontent.com/50ab28b3ef42d37fc3f8bec528f8fff73b75d359/68747470733a2f2f6c67746d2e696e2f702f304b4e344d744a5270" 
   alt="LGTM" 
   data-canonical-src="https://lgtm.in/p/0KN4MtJRp" 
   style="max-width:100%;">
```

I'm guessing something's broken with Github's proxy.
