### ISSUE TITLE
[Ask] Can I use the logo of lgtmin in my project ?

### ISSUE THREAD

**Issue by aiya000** [rahulsom/lgtmin#24]
Hi :smile:

I created [this repository](https://github.com/aiya000/franz-lgtm-in),
this is very easy project, a plugin for [franz](https://meetfranz.com/).

It only do to open the page of lgtm.in .

- - -

I want to use the logo of lgtm.in,
but I couldn't find the license about the logo.

Can I use the logo of lgtm.in in my project ? :thinking:

- - -

And sorry for ask this AS ISSUE 😭

**Comment by rahulsom** [comment]
https://github.com/rahulsom/lgtmin/blob/master/CREDITS.md links to the info on the icon.

**Comment by aiya000** [comment]
mmm, thanks 👍  !
